### ISSUE TITLE
Coherent Integration

### ISSUE THREAD

**Issue by saddieeiddas** [CUModSquad/Camelot-Unchained#240]
This is an issue to keep track of problems or ideas for coherent integration.

API
----

#### `client.ACCESS_TOKEN_PREFIX` is missing

Building
---------

#### How should `client.OnBlockSelected` be replaced

This is used by building UI to determine the shape/material of selected blocks

#### `game.plot.getBlocks` returns an array of materials not blocks

Should this potentially be renamed to `game.plot.getMaterials`?

Alternatively could the method be removed altogether and instead have a `game.plot.materials` property which is kept up to date with the array of materials?

---

**Comment by codecorsair** [comment]
Hijacking for client API status as well 🚗 

## Game Client API

### GameModel
 See [GameModel interface](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameInterface.ts#L22)
 
 - [ ] patchResourceChannel
 - [ ] accessToken
 - [ ] webAPIHost
 - [ ] serverHost
 - [ ] shardID
 - [ ] pktHash
 - [ ] reloadUI
 - [ ] quit
 - [ ] triggerKeyAction
 - [ ] sendSlashCommand
 - [ ] playGameSound
 - [ ] keybinds
 - [ ] clearKeybind
 - [ ] options
 - [ ] setOptionsreason
 - [ ] testOption
 - [ ] cancelTests
 - [ ] resetOptions
 - [ ] startItemPlacement
 - [ ] commitItemPlacement
 - [ ] resetItemPlacement
 - [ ] cancelItemPlacement
 - [ ] changeItemPlacementMode
 - [ ] _cse_dev_beginTriggerKeyActionLoop
 - [ ] _cse_dev_endTriggerKeyActionLoop

#### Game Model Tasks
> Methods that return a Task\<T> result
 - [ ] _cse_dev_bindKeyTask
 - [ ] _cse_dev_setOptions
 - [ ] _cse_dev_testOption
 - [ ] _cse_dev_takeScreenshot

### Engine Events
See [Engine Events](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/engineEvents.ts)

 - [ ] beginChat
 - [ ] systemMessage
 - [ ] scenarioRoundEnd
 - [ ] combatEvent
 - [ ] consoleText
 - [ ] updateDevUI
 - [ ] announcement
 - [ ] navigate
 - [ ] keybindChanged
 - [ ] optionChanged

### Entity States
See [EntityStateModel](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/EntityState.ts#L10).
#### Shared
 - [ ] Update event - `'entityState.update'`
 - [ ] faction
 - [ ] entityID
 - [ ] name
 - [ ] isAlive
 - [ ] position
 - [ ] statuses
 - [ ] health

#### PlayerState
 - [ ] type `'player'`
 - [ ] race
 - [ ] gender
 - [ ] class
 - [ ] stamina
 - [ ] blood
 - [ ] controlledEntityID

#### SiegeState
 - [ ] type `'siege'`
 - [ ] controllingEntityID

### Self Player State
See [SelfPlayerStateModel](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/PlayerState.ts#L17).
 Inherits all values of `PlayerState` from **Entity States**
 - [ ] Update event - `'selfPlayerState.update'`
 - [ ] name
 - [ ] characterID
 - [ ] serverPosition
 - [ ] facing
 - [ ] velocity
 - [ ] speed
 - [ ] horizontalSpeed
 - [ ] downCollisionAngle
 - [ ] terrainCollisionAngle
 - [ ] zoneID
 - [ ] respawn
 - [ ] stuck
 - [ ] changeZone
 - [ ] equipItem
 - [ ] unequipItem
 - [ ] requestFriendlyTarget
 - [ ] requestEnemyTarget

### Friendly Target Player State
See [FriendlyTargetPlayerStateModel interface](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/FriendlyTargetState.ts#L16).
 Inherits all values of `PlayerState` from **Entity States**
 - [ ] Update event - `'friendlyTargetPlayerState.update'`
 - [ ] characterID
 - [ ] isActive
 - [ ] position

### Enemy Target Player State
See [EnemyTargetPlayerStateModel interface](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/EnemyTargetState.ts#L16).
 Inherits all values of `PlayerState` from **Entity States**
 - [ ] Update event - `'enemyTargetPlayerState.update'`
 - [ ] characterID
 - [ ] isActive
 - [ ] position

### Key Actions

See [KeyActionsModel](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/KeyActions.ts#L14). 
Properties match the `ButtonFunction` enumeration found in `Input.h` on the game client. I will skip listing them all here.

### Loading State

See [LoadingStateModel](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/LoadingState.ts#L10).

 - [ ] percent
 - [ ] message
 - [ ] visible

### Plot

See [PlotModel](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/GameClientModels/Plot.ts#L10).

 - [ ] isOwner
 - [ ] permissions
 - [ ] ownerCharacterID
 - [ ] ownerEntityID
 - [ ] buildingMode
 - [ ] activeBlock
 - [ ] materials
 - [ ] setBuildingMode
 - [ ] selectBlock
 - [ ] replaceMaterials
 - [ ] replaceMaterialsInSelection
 - [ ] replaceShapes
 - [ ] replaceShapesInSelection
 - [ ] dropLight
 - [ ] resetLights
 - [ ] removeLight
 - [ ] countBlocks
 - [ ] selectBlueprint
 - [ ] getBlueprints
 - [ ] deleteBlueprint
 - [ ] createBlueprintFromSelection

### Client Tasks

 - [ ] Engine event `'taskComplete'`
 
#### Task type
See [Task<T> interface](https://github.com/CUModSquad/Camelot-Unchained/blob/coherent/library/src/game/clientTasks.ts#L29).
 - [ ] id
 - [ ] statusCode
 - [ ] value
 - [ ] errorMessage
 - [ ] cancel
